# DSのためのPython入門講座

## 6 はじめてのNumpy

[データサイエンスのためのPython入門⑥〜はじめてのNumpy〜 - 米国データサイエンティストのブログ](https://datawokagaku.com/numpy/)

### Numbers

In [1]:
import numpy as np

In [2]:
np.__version__

'2.4.1'

In [3]:
np.__config__.show()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.14.0/lib/python3.14/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.14.0/lib/python3.14/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.14.0/lib/python3.14/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.14.0/lib/python3.14/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.30
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    na

In [4]:
np.__file__

'/app/.venv/lib/python3.14/site-packages/numpy/__init__.py'

### NumPy Arrays

In [5]:
np_list = np.array([1, 2, 3])
np_list

array([1, 2, 3])

In [6]:
np_list = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
np_list

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [7]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [8]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [9]:
array1 - array2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

`*`はアダマール積

In [10]:
array1 * array2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [11]:
array1 / array2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

行列のサイズが合わない場合 → 自動的に **補完(Broadcasting)** される

In [12]:
array1 = np.array([1, 2]) # 1x2
array2 = np.array([[1, 2], [3, 4], [5, 6]]) # 3x2

In [13]:
array1 + array2

array([[2, 4],
       [4, 6],
       [6, 8]])

In [14]:
array1 - array2

array([[ 0,  0],
       [-2, -2],
       [-4, -4]])

In [15]:
array1 * array2

array([[ 1,  4],
       [ 3,  8],
       [ 5, 12]])

In [16]:
array1 / array2

array([[1.        , 1.        ],
       [0.33333333, 0.5       ],
       [0.2       , 0.33333333]])

行ベクトルの次元が異なるのはダメ

In [17]:
array1 = np.array([1, 2]) # 1x2
array2 = np.array([1, 2, 3]) # 1x3

In [18]:
array1 + array2

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [19]:
array1 = np.array([1, 2, 3, 4]) # 1x4
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # 3x3

In [20]:
array1 + array2

ValueError: operands could not be broadcast together with shapes (4,) (3,3) 

In [21]:
array = np.array([[1, 2], [2, 4], [3, 5]])
print(array)
array.shape

[[1 2]
 [2 4]
 [3 5]]


(3, 2)

## 7 NumPyのindexingとslicing

[データサイエンスのためのPython入門⑦〜これだけ知っておけばいいNumPyのindexingとslicing〜 - 米国データサイエンティストのブログ](https://datawokagaku.com/numpy_slice/)

### Indexing

In [22]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
print(ndarray[1][0])
print(ndarray[1, 0])

3
3


In [24]:
ndarray = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]], [[13, 14], [15, 16], [17, 18]]])
print(ndarray.shape)
ndarray

(3, 3, 2)


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [25]:
ndarray[1]

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [26]:
ndarray[1, 2]

array([11, 12])

In [27]:
ndarray[1, 2, 0]

np.int64(11)

### Slicing

In [28]:
array = np.array([[1, 2, 3, 4], [2, 4, 6, 4], [3, 5, 7, 4], [3, 5, 7, 4]])
array

array([[1, 2, 3, 4],
       [2, 4, 6, 4],
       [3, 5, 7, 4],
       [3, 5, 7, 4]])

In [29]:
array[:, 2:]

array([[3, 4],
       [6, 4],
       [7, 4],
       [7, 4]])

In [30]:
array = np.array([1, 2, 3, 4, 5, 6, 7])
print(array[1:6])
print(array[1:6:2])

[2 3 4 5 6]
[2 4 6]


## 8 NumPyでよく使う行列生成

[データサイエンスのためのPython入門⑧〜NumPyでよく使う行列生成〜 - 米国データサイエンティストのブログ](https://datawokagaku.com/numpy_generate/)

### np.arange([start,] stop[, step])

In [31]:
np.arange(0, 7, 2)

array([0, 2, 4, 6])

In [32]:
np.arange(5) # np.arange(0, 5, 1)

array([0, 1, 2, 3, 4])

In [33]:
np.arange(2, 5) # np.arange(2, 5, 1)

array([2, 3, 4])

### np.linspace(start, stop, num=50)

In [34]:
np.linspace(1, 2, 20)

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

### .copy()

In [35]:
array1 = np.arange(5)
array2 = array.copy()

コピーしたのでIDが異なる

In [36]:
print(id(array1))
print(id(array2))

139712804461936
139713545076624


元のベクトルを改変しても、コピーしたベクトルは変わらない。

In [37]:
array1[:] = 100
print(array1)
print(array2)

[100 100 100 100 100]
[1 2 3 4 5 6 7]


### np.zeros(shape)

In [38]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [39]:
shape = (2, 3, 5)
np.zeros(shape)

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

### np.ones(shape)

In [40]:
np.ones(3)

array([1., 1., 1.])

In [41]:
shape = (2, 3, 5)
np.ones(shape)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

### np.eye(N)

In [42]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

### 乱数生成

**補足**：NumPy1.17(2019/7)以降は`Generator`を利用する方法が推奨されている。

- `random.Generator.random(size=None, dtype=np.float64, out=None)`メソッド: 連続一様分布
- `random.Generator.normal(loc=0.0, scale=1.0, size=None)`メソッド: 正規分布
- `random.Generator.integers(low, high=None, size=None, dtype=np.int64, endpoint=False)`メソッド: 離散一様分布

In [44]:
rng = np.random.default_rng(1728)

### random.Generator.random(size=None, dtype=np.float64, out=None)

In [45]:
rng.random()

0.7665956828605809

In [46]:
rng.random(3)

array([0.70205733, 0.90198099, 0.71490011])

In [47]:
rng.random((3, 5))

array([[0.88257145, 0.38708815, 0.57039805, 0.06785435, 0.96371112],
       [0.38372161, 0.48313711, 0.91768683, 0.256912  , 0.26640058],
       [0.17231641, 0.24785465, 0.5566607 , 0.18492172, 0.38200515]])

### random.Generator.normal(loc=0.0, scale=1.0, size=None)

In [48]:
rng.normal()

-0.15273350193350402

In [49]:
rng.normal(size=3)

array([ 1.51639808, -1.95148312,  1.02485433])

In [50]:
rng.normal(size=(3, 4))

array([[-1.41426816, -0.42325657,  1.40363505,  0.35663045],
       [-0.40824753,  0.93338735,  0.45316263, -0.32732742],
       [ 1.02581572, -1.20693684,  0.88650372, -0.2765314 ]])

### random.Generator.integers(low, high=None, size=None, dtype=np.int64, endpoint=False)

In [51]:
rng.integers(10, 50, 10)

array([45, 24, 32, 18, 14, 44, 12, 24, 23, 17])

In [52]:
rng.integers(10, 50, (2, 4, 3))

array([[[31, 46, 27],
        [45, 22, 18],
        [27, 11, 46],
        [20, 41, 18]],

       [[35, 33, 33],
        [41, 45, 47],
        [31, 17, 42],
        [13, 15, 33]]])

### .reshape(shape)

In [53]:
array = np.arange(0, 10)
print('shape:\n{}'.format(array.shape))
print('array:\n{}'.format(array))

reshaped_array = array.reshape((2, 5))
print('shape:\n{}'.format(reshaped_array.shape))
print('array:\n{}'.format(reshaped_array))

print('original array:\n{}'.format(array))

shape:
(10,)
array:
[0 1 2 3 4 5 6 7 8 9]
shape:
(2, 5)
array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
original array:
[0 1 2 3 4 5 6 7 8 9]


更に変形する。

In [54]:
reshaped_array = reshaped_array.reshape((5, 2))
print('shape:\n{}'.format(reshaped_array.shape))
print('array:\n{}'.format(reshaped_array))

shape:
(5, 2)
array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


## 9 NumPyでよく使う便利関数

[データサイエンスのためのPython入門⑨〜NumPyでよく使う便利関数〜 - 米国データサイエンティストのブログ](https://datawokagaku.com/numpy_functions/)

In [55]:
normal_dist_mat = rng.normal(size=(5, 5))
print(normal_dist_mat)

[[ 3.50599397e+00  2.66545542e-01 -1.51562073e-03  9.31402759e-01
  -1.37920364e+00]
 [ 5.50924678e-01 -9.84326299e-01 -1.22293662e+00  8.68974211e-02
  -9.41343198e-01]
 [-2.32656092e-01  5.39282814e-01  1.37514214e+00  1.01340110e+00
  -7.66450602e-01]
 [ 1.56164756e-01 -1.90582579e-01  1.63237998e+00  1.01817192e+00
   5.26714341e-01]
 [-1.31963418e+00  1.01747533e+00  1.97345221e+00  1.81499915e+00
  -1.15853188e+00]]


### .max()と.argmax()

In [56]:
print('max is {}'.format(normal_dist_mat.max()))
print('argmax is {}'.format(normal_dist_mat.argmax()))

max is 3.505993968396396
argmax is 0


In [57]:
normal_dist_mat.flatten()[15]

np.float64(0.15616475610756414)

### .min()と.argmin()

In [58]:
print('min is {}'.format(normal_dist_mat.min()))
print('argmin is {}'.format(normal_dist_mat.argmin()))

min is -1.3792036388459263
argmin is 4


### .mean()

In [59]:
print('mean is {}'.format(normal_dist_mat.mean()))

mean is 0.32847069662036477


### np.median(ndarray)

メソッドでなく **関数** なのに注意！

In [60]:
print('median is {}'.format(np.median(normal_dist_mat)))

median is 0.26654554223461724


### .std()

In [61]:
print('standard deviation is {}'.format(normal_dist_mat.std()))

standard deviation is 1.1881851117105249


### 引数axis

- `axis=0`: 各列の統計量
- `axis=1`: 各行の統計量

In [62]:
print(normal_dist_mat)
print('axis=0> {}'.format(normal_dist_mat.max(axis=0)))
print('axis=1> {}'.format(normal_dist_mat.max(axis=1)))

[[ 3.50599397e+00  2.66545542e-01 -1.51562073e-03  9.31402759e-01
  -1.37920364e+00]
 [ 5.50924678e-01 -9.84326299e-01 -1.22293662e+00  8.68974211e-02
  -9.41343198e-01]
 [-2.32656092e-01  5.39282814e-01  1.37514214e+00  1.01340110e+00
  -7.66450602e-01]
 [ 1.56164756e-01 -1.90582579e-01  1.63237998e+00  1.01817192e+00
   5.26714341e-01]
 [-1.31963418e+00  1.01747533e+00  1.97345221e+00  1.81499915e+00
  -1.15853188e+00]]
axis=0> [3.50599397 1.01747533 1.97345221 1.81499915 0.52671434]
axis=1> [3.50599397 0.55092468 1.37514214 1.63237998 1.97345221]


### np.exp(ndarray)

In [63]:
ndarray = np.linspace(-3, 3, 10)
exp_ndarray = np.exp(ndarray)
print(ndarray)
print(exp_ndarray)

[-3.         -2.33333333 -1.66666667 -1.         -0.33333333  0.33333333
  1.          1.66666667  2.33333333  3.        ]
[ 0.04978707  0.09697197  0.1888756   0.36787944  0.71653131  1.39561243
  2.71828183  5.29449005 10.3122585  20.08553692]


### np.log(ndarray)

In [64]:
ndarray = np.linspace(-3, 3, 10)
log_ndarray = np.log(ndarray)
print(ndarray)
print(log_ndarray)

[-3.         -2.33333333 -1.66666667 -1.         -0.33333333  0.33333333
  1.          1.66666667  2.33333333  3.        ]
[        nan         nan         nan         nan         nan -1.09861229
  0.          0.51082562  0.84729786  1.09861229]


/tmp/ipykernel_1469/3321249551.py:2: RuntimeWarning: invalid value encountered in log
  log_ndarray = np.log(ndarray)


### np.nan と np.isnan()

**注意**：`nan`(Not-A-Number)と`None`は異なる

In [65]:
print('non == None?: {}'.format(np.nan is None))

non == None?: False


`nan`かどうかは`np.isnan()`関数でチェックする

In [66]:
print(log_ndarray[0])
print(np.isnan(log_ndarray[0]))

nan
True


`== np.nan`や`is np.nan`ではダメ！

In [67]:
log_ndarray[0] == np.nan

np.False_

In [68]:
log_ndarray[0] is np.nan

False

### np.e

In [69]:
print(np.e)
print(np.log(np.e))

2.718281828459045
1.0


### ndarrayのshape操作

In [70]:
ndarray = np.arange(1, 10).reshape(3, 3)
print('array is:\n{}'.format(ndarray))
print('shape is: {}'.format(ndarray.shape))

array is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape is: (3, 3)


#### np.expand_dims(ndarray, axis)

In [71]:
expanded_ndarray = np.expand_dims(ndarray, axis=0)
expanded_ndarray.shape

(1, 3, 3)

In [72]:
expanded_ndarray

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [73]:
expanded_ndarray = np.expand_dims(ndarray, axis=-1)
expanded_ndarray.shape

(3, 3, 1)

In [74]:
expanded_ndarray

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [75]:
expanded_ndarray[:,:,0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### np.squeeze(ndarray)

サイズが1の次元をまとめて削除する

In [76]:
expanded_ndarray = np.expand_dims(ndarray, axis=0)
expanded_ndarray.shape

(1, 3, 3)

In [77]:
squeezed_expanded_ndarray = np.squeeze(expanded_ndarray)
squeezed_expanded_ndarray.shape

(3, 3)

In [78]:
squeezed_expanded_ndarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
expanded_ndarray = np.expand_dims(ndarray, axis=-1)
expanded_ndarray.shape

(3, 3, 1)

In [80]:
squeezed_expanded_ndarray = np.squeeze(expanded_ndarray)
squeezed_expanded_ndarray.shape

(3, 3)

In [81]:
squeezed_expanded_ndarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### .flatten()

In [82]:
ndarray = np.arange(1, 10).reshape(3, 3)
ndarray.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### np.save & np.load

In [83]:
np.save('saved_ndarray', ndarray)

In [84]:
loaded_ndarray = np.load('saved_ndarray.npy')
loaded_ndarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])